# Generated by Django 5.2.4 on 2025-07-24 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cover',
            field=models.ImageField(default=1, upload_to='media/images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='promo_video',
            field=models.FileField(blank=True, null=True, upload_to='media/videos'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(upload_to='media/avatars'),
        ),
    ]
