# Generated by Django 5.2.4 on 2025-07-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0003_alter_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cover',
            field=models.ImageField(default=1, upload_to='media/categories'),
            preserve_default=False,
        ),
    ]
