# Generated by Django 5.2.4 on 2025-07-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='area',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
