# Generated by Django 5.2.4 on 2025-07-31 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
